Repository AdoptOpenJDK/IcedTea-Web, pull requests merged in 2019-04, with the labels that each got.

#14 Allow installer to be built on AdoptOpenJDK infra
  Makefile.am
Labels: enhancement

#13 Packed resources are unnecessarily cached after unpacking
  netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
Labels: bug

#12 Packed resources are stored in cache with double file extension
  netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
Labels: bug

#11 IcedTea-Web always redownloads web start application if they are packed
  netx/net/sourceforge/jnlp/cache/CacheEntry.java
  netx/net/sourceforge/jnlp/cache/ResourceDownloader.java
  tests/netx/unit/net/sourceforge/jnlp/cache/CacheEntryTest.java
Labels: bug

#3 Task #3711 - jre of the properties file does not work under windows
  netx/net/sourceforge/jnlp/controlpanel/JVMPanel.java
  rust-launcher/src/property.rs
  rust-launcher/src/property_from_file.rs
  rust-launcher/src/property_from_files_resolver.rs
Labels: bug

#119 First modules defined
  common/pom.xml
  common/src/main/java/net/sourceforge/jnlp/util/replacements/BASE64Decoder.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/BASE64Encoder.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/CharacterDecoder.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/CharacterEncoder.java
  common/src/main/java/net/sourceforge/jnlp/util/ui/NonEditableTableModel.java
  common/src/main/java/net/sourceforge/jnlp/util/ui/package-info.java
  core/pom.xml
  jnlp-api/pom.xml
  jnlp-api/src/main/java/javax/jnlp/BasicService.java
  jnlp-api/src/main/java/javax/jnlp/ClipboardService.java
  jnlp-api/src/main/java/javax/jnlp/DownloadService.java
  jnlp-api/src/main/java/javax/jnlp/DownloadService2.java
  jnlp-api/src/main/java/javax/jnlp/DownloadServiceListener.java
  jnlp-api/src/main/java/javax/jnlp/ExtendedService.java
  jnlp-api/src/main/java/javax/jnlp/ExtensionInstallerService.java
  jnlp-api/src/main/java/javax/jnlp/FileContents.java
  jnlp-api/src/main/java/javax/jnlp/FileOpenService.java
  jnlp-api/src/main/java/javax/jnlp/FileSaveService.java
  jnlp-api/src/main/java/javax/jnlp/IntegrationService.java
  jnlp-api/src/main/java/javax/jnlp/JNLPRandomAccessFile.java
  jnlp-api/src/main/java/javax/jnlp/PersistenceService.java
  jnlp-api/src/main/java/javax/jnlp/PrintService.java
  jnlp-api/src/main/java/javax/jnlp/ServiceManager.java
  jnlp-api/src/main/java/javax/jnlp/ServiceManagerStub.java
  jnlp-api/src/main/java/javax/jnlp/SingleInstanceListener.java
  jnlp-api/src/main/java/javax/jnlp/SingleInstanceService.java
  jnlp-api/src/main/java/javax/jnlp/UnavailableServiceException.java
  pom.xml
Labels: enhancement

#121 first simple readme added
  README.md
Labels: enhancement

#120 code of conduction & styleguide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  JAVA_STYLE_GUIDE.md
Labels: enhancement

#125 move Translator to common module
  common/src/main/java/net/sourceforge/jnlp/runtime/Translator.java
  core/src/main/java/net/sourceforge/jnlp/config/BasicValueValidators.java
  core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
  core/src/main/java/net/sourceforge/jnlp/services/XBasicService.java
Labels: enhancement

#127 Options definitions split
  common/src/main/java/net/adoptopenjdk/icedteaweb/option/OptionsDefinitions.java
  core/src/main/java/net/sourceforge/jnlp/ParseException.java
  core/src/main/java/net/sourceforge/jnlp/ParserSettings.java
  core/src/main/java/net/sourceforge/jnlp/XMLParser.java
  core/src/main/java/net/sourceforge/jnlp/browser/FirefoxPreferencesFinder.java
  core/src/main/java/net/sourceforge/jnlp/browser/FirefoxPreferencesParser.java
  core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
  core/src/main/java/net/sourceforge/jnlp/controlpanel/CommandLine.java
  core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
  core/src/main/java/net/sourceforge/jnlp/runtime/HtmlBoot.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/html/AppletExtractor.java
  core/src/main/java/net/sourceforge/jnlp/security/dialogs/InetSecurity511Panel.java
  core/src/main/java/net/sourceforge/jnlp/security/policyeditor/PolicyEditor.java
  core/src/main/java/net/sourceforge/jnlp/services/XBasicService.java
  core/src/main/java/net/sourceforge/jnlp/util/OptionsDefinitionsPrinter.java
  core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/ItwebSettingsTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/JavaWsTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/PolicyEditorTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/TextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/optionparser/OptionParser.java
  core/src/main/java/net/sourceforge/jnlp/util/optionparser/ParsedOption.java
  core/src/test/java/net/sourceforge/jnlp/ParserSettingsTest.java
  core/src/test/java/net/sourceforge/jnlp/ServerAccess.java
  core/src/test/java/net/sourceforge/jnlp/controlpanel/CommandLineTest.java
  core/src/test/java/net/sourceforge/jnlp/security/policyeditor/PolicyEditorTest.java
  core/src/test/java/net/sourceforge/jnlp/util/optionparser/OptionParserTest.java
Labels: enhancement

#126 refactoring of *Desc classes
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  JAVA_STYLE_GUIDE.md
  core/src/main/java/net/sourceforge/jnlp/AppletDesc.java
  core/src/main/java/net/sourceforge/jnlp/ApplicationDesc.java
  core/src/main/java/net/sourceforge/jnlp/AssociationDesc.java
  core/src/main/java/net/sourceforge/jnlp/IconDesc.java
  core/src/main/java/net/sourceforge/jnlp/InstallerDesc.java
  core/src/main/java/net/sourceforge/jnlp/JARDesc.java
  core/src/main/java/net/sourceforge/jnlp/JNLPFileFactory.java
  core/src/main/java/net/sourceforge/jnlp/JREDesc.java
  core/src/main/java/net/sourceforge/jnlp/MenuDesc.java
  core/src/main/java/net/sourceforge/jnlp/PackageDesc.java
  core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
  core/src/main/java/net/sourceforge/jnlp/PropertyDesc.java
  core/src/main/java/net/sourceforge/jnlp/RelatedContentDesc.java
  core/src/main/java/net/sourceforge/jnlp/ResourcesDesc.java
  core/src/main/java/net/sourceforge/jnlp/ShortcutDesc.java
  core/src/main/java/net/sourceforge/jnlp/UpdateDesc.java
  core/src/test/java/net/sourceforge/jnlp/PluginBridgeTest.java
Labels: enhancement

#114 Windows desktop shortcut contains wrong target if javaws.exe is accessible via the path
  core/src/main/java/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
  core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
Labels: bug

#133 Security refactoring
  core/src/main/java/net/sourceforge/jnlp/security/CertificateUtils.java
  core/src/main/java/net/sourceforge/jnlp/security/VariableX509TrustManager.java
Labels: enhancement

#131 Jdk89acesses to common
  common/src/main/java/net/adoptopenjdk/icedteaweb/jdk89access/JarIndexAccess.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/jdk89access/SunMiscLauncher.java
  core/src/main/java/net/sourceforge/jnlp/jdk89acesses/JarIndexAccess.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/security/dialogs/AccessWarningPane.java
  core/src/main/java/net/sourceforge/jnlp/security/dialogs/CertWarningPane.java
  core/src/main/java/net/sourceforge/jnlp/security/dialogs/MoreInfoPane.java
Labels: enhancement

#150 decouple deployment configuration from legacy and swing dependency
  core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
  core/src/main/java/net/sourceforge/jnlp/controlpanel/CommandLine.java
  core/src/main/java/net/sourceforge/jnlp/controlpanel/ControlPanel.java
  core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
Labels: enhancement

#157 Extracted more UI components to client package
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/PolicyPanel.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/FileDialogFactory.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/downloadindicator/DefaultDownloadIndicator.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/downloadindicator/DownloadIndicator.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyEditor.java
  core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPRuntime.java
Labels: enhancement

#160 refactoring of config package based on IntelliJ Analyzer
  core/src/main/java/net/sourceforge/jnlp/config/BasicValueValidators.java
  core/src/main/java/net/sourceforge/jnlp/config/ConfiguratonValidator.java
  core/src/main/java/net/sourceforge/jnlp/config/Defaults.java
  core/src/main/java/net/sourceforge/jnlp/config/DeploymentConfiguration.java
  core/src/main/java/net/sourceforge/jnlp/config/DirectoryValidator.java
  core/src/main/java/net/sourceforge/jnlp/config/InfrastructureFileDescriptor.java
  core/src/main/java/net/sourceforge/jnlp/config/PathsAndFiles.java
  core/src/main/java/net/sourceforge/jnlp/config/Target.java
  core/src/main/java/net/sourceforge/jnlp/config/ValueValidator.java
Labels: enhancement

#161 refactoring of xmlparser package based on IntelliJ Analyzer
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/ElementName.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/MalformedXMLParser.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/Node.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/XMLElement.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/XMLParseException.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/XMLParser.java
Labels: enhancement

#153 Adjustments to the msi-installer:
  Makefile.am
  acinclude.m4
  win-installer/installer.json.in
Labels: enhancement

#166 Renamed msi to have versioned name
  Makefile.am
Labels: bug

#169 Group jnlp element desc's logically as described in JSR
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/GuiLaunchHandler.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/DesktopShortcutPanel.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/AccessWarningPane.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/appletextendedsecurity/UnsignedAppletTrustConfirmation.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InfoItem.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InformationElement.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/LaunchDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/extension/ComponentDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/extension/InstallerDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/AssociationDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/IconDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/MenuDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/RelatedContentDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/ShortcutDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ExtensionDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JARDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/PackageDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/PropertyDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ResourcesDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateDesc.java
  core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
  core/src/main/java/net/sourceforge/jnlp/Launcher.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
  core/src/main/java/net/sourceforge/jnlp/config/Defaults.java
  core/src/main/java/net/sourceforge/jnlp/runtime/AppletEnvironment.java
  core/src/main/java/net/sourceforge/jnlp/runtime/ApplicationInstance.java
  core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/LocateJnlpClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/ManageJnlpResources.java
  core/src/main/java/net/sourceforge/jnlp/runtime/ManifestAttributesChecker.java
  core/src/main/java/net/sourceforge/jnlp/services/XBasicService.java
  core/src/main/java/net/sourceforge/jnlp/services/XDownloadService.java
  core/src/main/java/net/sourceforge/jnlp/tools/JarCertVerifier.java
  core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/SecurityDialogsTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/appletextendedsecurity/UnsignedAppletTrustConfirmationTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDescTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDescTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ResourcesDescTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDescTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/mock/DummyJNLPFile.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/mock/DummyJNLPFileWithJar.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/mock/MockJNLPFile.java
  core/src/test/java/net/sourceforge/jnlp/JNLPFileTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserBasicTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserTest.java
  core/src/test/java/net/sourceforge/jnlp/PluginBridgeTest.java
  core/src/test/java/net/sourceforge/jnlp/PropertyDescTest.java
  core/src/test/java/net/sourceforge/jnlp/runtime/CodeBaseClassLoaderTest.java
  core/src/test/java/net/sourceforge/jnlp/runtime/JNLPClassLoaderTest.java
  core/src/test/java/net/sourceforge/jnlp/runtime/JNLPFileTest.java
  core/src/test/java/net/sourceforge/jnlp/tools/JarCertVerifierTest.java
  core/src/test/java/net/sourceforge/jnlp/util/XDesktopEntryTest.java
Labels: enhancement

#167 JNLP VersionId and VersionString implementation
  common/src/main/java/net/adoptopenjdk/icedteaweb/IcedTeaWebConstants.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/JNLPVersionSpecifications.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionId.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionModifier.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionSeparator.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionString.java
  common/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionIdTest.java
  common/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionStringTest.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ExtensionDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JARDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/JREDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/JreVersion.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/Version.java
  core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
  core/src/main/java/net/sourceforge/jnlp/JNLPFileFactory.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
  core/src/main/java/net/sourceforge/jnlp/cache/CacheEntry.java
  core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
  core/src/main/java/net/sourceforge/jnlp/cache/Resource.java
  core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
  core/src/main/java/net/sourceforge/jnlp/cache/ResourceTracker.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPRuntime.java
  core/src/main/java/net/sourceforge/jnlp/runtime/LocateJnlpClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/ManageJnlpResources.java
  core/src/main/java/net/sourceforge/jnlp/services/XDownloadService.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/version/VersionTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/mock/DummyJNLPFileWithJar.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/tools/CodeSignerCreator.java
  core/src/test/java/net/sourceforge/jnlp/PluginBridgeTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/CacheEntryTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/NativeLibraryStorageTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceDownloaderTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceTrackerTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceUrlCreatorTest.java
Labels: enhancement

#170 refactored update element and update attributes
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateCheck.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdatePolicy.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
Labels: enhancement, good first issue

#172 use ico-file instead of png-file as itw-icon and use it as default icon
  Makefile.am
  launchers/javaws.ico
  win-installer/installer.json.in
Labels: bug

#173 use ico-file instead of png-file as itw-icon and use it as default icon
  launchers/javaws.ico
  launchers/win-installer/installer.json.in
Labels: bug

#175 refactored application/applet descriptor elements
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/EntryPoint.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/LaunchDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/AppletDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/application/ApplicationType.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/extension/InstallerDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateCheck.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdatePolicy.java
  core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
  core/src/main/java/net/sourceforge/jnlp/runtime/AppletEnvironment.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPClassLoader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/ManifestAttributesChecker.java
  core/src/main/java/net/sourceforge/jnlp/services/XBasicService.java
  core/src/main/java/net/sourceforge/jnlp/util/AppletUtils.java
  core/src/test/java/net/sourceforge/jnlp/ParserBasicTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserCornerCasesTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserTest.java
Labels: enhancement

#176 moved generic XML parsing functionality from JNLP Parser to XMLParser
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  core/src/main/java/net/sourceforge/jnlp/runtime/html/AppletParser.java
  core/src/test/java/net/sourceforge/jnlp/ParserTest.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/XMLParser.java
Labels: enhancement

#171 Replace BASE64 Encoder and Decoder with Java8 implementation
  common/src/main/java/net/adoptopenjdk/icedteaweb/io/IOUtils.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/os/OsUtil.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/BASE64Decoder.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/BASE64Encoder.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/CharacterDecoder.java
  common/src/main/java/net/sourceforge/jnlp/util/replacements/CharacterEncoder.java
  core/src/main/java/net/sourceforge/jnlp/PluginBridge.java
  core/src/main/java/net/sourceforge/jnlp/security/CertificateUtils.java
  core/src/test/java/net/sourceforge/jnlp/PluginBridgeTest.java
  core/src/test/java/net/sourceforge/jnlp/util/replacements/BASE64DecoderTest.java
  core/src/test/java/net/sourceforge/jnlp/util/replacements/BASE64EncoderTest.java
Labels: enhancement

#177 extract StringUtils
  common/pom.xml
  common/src/main/java/net/adoptopenjdk/icedteaweb/Assert.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/StringUtils.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/io/IOUtils.java
  common/src/test/java/net/adoptopenjdk/icedteaweb/StringUtilsTest.java
Labels: enhancement

#178 isolate pure locale handling functionality into LocaleUtils
  core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  core/src/main/java/net/sourceforge/jnlp/util/LocaleUtils.java
  core/src/test/java/net/sourceforge/jnlp/JNLPFileTest.java
  core/src/test/java/net/sourceforge/jnlp/util/LocaleUtilsTest.java
Labels: enhancement

#182 isolated pure JVM argument checking functionality into JVMUtils
  common/src/main/java/net/adoptopenjdk/icedteaweb/jvm/JVMUtils.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
Labels: enhancement

#186 simplified code in JvmUtils
  common/src/main/java/net/adoptopenjdk/icedteaweb/jvm/JvmUtils.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
Labels: enhancement

#179 Refactored jnlp information element
  common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages.properties
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/GuiLaunchHandler.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/DescriptionInfoItem.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InfoItem.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InformationElement.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/AssociationDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/DescriptionDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/DescriptionKind.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/HomepageDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/IconDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/IconKind.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/MenuDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/RelatedContentDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/ShortcutDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/resource/ResourcesDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateCheck.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdateDesc.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/update/UpdatePolicy.java
  core/src/main/java/net/sourceforge/jnlp/JNLPFile.java
  core/src/main/java/net/sourceforge/jnlp/Parser.java
  core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/ErrorSplashScreenTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/SplashScreenTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/DescriptionInfoItemTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InfoItemTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InformationElementTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/DescriptionKindTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/IconKindTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/jnlp/element/information/InformationDescTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserBasicTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserCornerCasesTest.java
  core/src/test/java/net/sourceforge/jnlp/ParserTest.java
Labels: enhancement

#180 Handle jnlp filename with space for shortcuts
  netx/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
Labels: bug

#188 Handle jnlp filename with space for shortcuts
  common/src/main/java/net/adoptopenjdk/icedteaweb/IcedTeaWebConstants.java
  core/src/main/java/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
Labels: bug

#183 Refactor resource downloader
  core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceDownloaderTest.java
Labels: enhancement

#193 Console buttons spacing
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
Labels: enhancement

#189 PolicyFileModel fails to parse the locked policy files on Windows
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyFileModel.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyFileModelTest.java
Labels: bug, question

#192 introduce CloseableConnection
  common/src/main/java/net/adoptopenjdk/icedteaweb/http/CloseableConnection.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/http/CloseableHttpConnection.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/http/ConnectionFactory.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/http/HttpMethod.java
  common/src/main/java/net/adoptopenjdk/icedteaweb/http/HttpUtils.java
  common/src/test/java/net/adoptopenjdk/icedteaweb/http/HttpUtilsTest.java
  core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
  core/src/main/java/net/sourceforge/jnlp/cache/ResourceDownloader.java
  core/src/main/java/net/sourceforge/jnlp/runtime/CachedJarFileCallback.java
  core/src/main/java/net/sourceforge/jnlp/security/ConnectionFactory.java
  core/src/test/java/net/sourceforge/jnlp/util/HttpUtilsTest.java
Labels: enhancement

#201 Read/Write the policy files with the UTF-8 encoding
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyFileModel.java
Labels: bug

#208 Launchers from pom
  launchers/build.sh
  launchers/configure.sh
  launchers/pom.xml
  launchers/rust-launcher/src/hardcoded_paths.rs
  launchers/rust-launcher/src/jars_helper.rs
  launchers/rust-launcher/src/main.rs
  launchers/rust-launcher/src/property_from_file.rs
  launchers/rust-launcher/src/utils.rs
  launchers/shell-launcher/launchers.sh.in
Labels: enhancement

#209 replace Property- and FilePermission with values from SecurityConstants
  core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDesc.java
  core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
  core/src/main/java/net/sourceforge/jnlp/runtime/RhinoBasedPacEvaluator.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/TemporaryPermissionsTest.java
Labels: enhancement

#210 use Charset instead of String for encoding
  common/src/main/java/net/adoptopenjdk/icedteaweb/EncodingConstants.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/commandline/CommandLine.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/console/JavaConsole.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/controlpanel/UnsignedAppletsTrustingListPanel.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/browser/HtmlBrowserPanel.java
  core/src/main/java/net/adoptopenjdk/icedteaweb/client/policyeditor/PolicyEditor.java
  core/src/main/java/net/sourceforge/jnlp/cache/CacheUtil.java
  core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java
  core/src/main/java/net/sourceforge/jnlp/runtime/JNLPPolicy.java
  core/src/main/java/net/sourceforge/jnlp/util/FileUtils.java
  core/src/main/java/net/sourceforge/jnlp/util/StreamUtils.java
  core/src/main/java/net/sourceforge/jnlp/util/UrlUtils.java
  core/src/main/java/net/sourceforge/jnlp/util/WindowsDesktopEntry.java
  core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/IcedTeaWebTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/ItwebPluginTextProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/ItwebSettingsTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/JavaWsTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/PolicyEditorTextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/TextsProvider.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/Formatter.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/HtmlFormatter.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/ManFormatter.java
  core/src/main/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/PlainTextFormatter.java
  core/src/main/java/net/sourceforge/jnlp/util/lockingfile/LockingReaderWriter.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/parts/InformationElementTest.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/ContentReader.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/ServerAccess.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/ThreadedProcess.java
  core/src/test/java/net/adoptopenjdk/icedteaweb/testing/TinyHttpdImpl.java
  core/src/test/java/net/sourceforge/jnlp/JNLPMatcherTest.java
  core/src/test/java/net/sourceforge/jnlp/JNLPMatcherTestMalformedAllowedTest.java
  core/src/test/java/net/sourceforge/jnlp/ResourcesTest.java
  core/src/test/java/net/sourceforge/jnlp/TinyHttpdImplTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceDownloaderTest.java
  core/src/test/java/net/sourceforge/jnlp/cache/ResourceTrackerTest.java
  core/src/test/java/net/sourceforge/jnlp/util/docprovider/ReadAuthorsTest.java
  core/src/test/java/net/sourceforge/jnlp/util/docprovider/formatters/formatters/ReplacingTextFormatterTest.java
  core/src/test/java/net/sourceforge/jnlp/util/logging/OutputControllerTest.java
  core/src/test/java/net/sourceforge/jnlp/util/logging/PrintStreamLoggerTest.java
  core/src/test/java/net/sourceforge/jnlp/util/logging/TeeOutputStreamTest.java
  xml-parser/src/main/java/net/adoptopenjdk/icedteaweb/xmlparser/XMLParser.java
Labels: enhancement
